import type { Key } from "./uk.ts";

export const en: Record<Key, string> = {
  "meta.title": "Fineko — AI Sales Agent & CRM for Instagram Shops",
  "nav.how": "How it works", "nav.crm": "CRM", "nav.results": "Results", "nav.pricing": "Pricing",
  "hero.badge": "Live in production — not a demo, not an MVP",
  "hero.title": "An AI salesperson and <em>CRM</em> for Instagram shops",
  "hero.lede": "A turnkey solution: the AI handles the conversation, places orders and reconciles payments — while the CRM shows everything happening in your business.",
  "hero.cta1": "See how it works", "hero.cta2": "Estimate your savings", "hero.scroll": "Scroll ↓",

  "problem.k": "The problem",
  "problem.title": "Instagram sales hit a human ceiling",
  "problem.intro": "Every customer in Direct means manual work: picking the item, checking payment, the address, the waybill. While your manager sleeps, takes lunch or drowns in messages, sales go to competitors.",
  "clock.1": "Customer writes: “Do you have this dress in M?”",
  "clock.2": "Silence. The manager has gone home.",
  "clock.3": "The customer buys from another shop.",
  "clock.4": "A reply arrives — but it's too late.",
  "p1.t": "A customer writes at 23:47", "p1.d": "The reply comes in the morning. They've already bought elsewhere.",
  "p2.t": "The manager can't keep up", "p2.d": "Size, colour, payment check, address, waybill — all by hand, for every single customer.",
  "p3.t": "Mistakes under pressure", "p3.d": "Wrong size, a forgotten payment, a message lost in the day's flood.",
  "p4.t": "Salary is a fixed cost", "p4.d": "No matter how many customers wrote in this month.",
  "p5.t": "The owner can't see the picture", "p5.d": "Which ad drove how many sales, which products get asked about most, where the bot gets stuck.",

  "sys.k": "The solution",
  "sys.title": "One system, two engines",
  "sys.intro": "Fineko is an AI agent that runs Instagram Direct conversations from the first message to shipping, plus a CRM that manages products, analytics and the knowledge base behind it. Neither works as well without the other.",
  "sys.a.tag": "AI agent", "sys.a.d": "A salesperson who never sleeps. Takes the customer from the first message to a placed order and waybill tracking — fully automatically.",
  "sys.a.l1": "Replies in Direct instantly, 24/7", "sys.a.l2": "Places orders and reconciles payments", "sys.a.l3": "Hands tricky cases to a human",
  "sys.b.tag": "CRM", "sys.b.d": "The brain and control panel of the business. Products, knowledge base, sales and ad analytics — all in one place, no Excel.",
  "sys.b.l1": "Product catalog with variants", "sys.b.l2": "Knowledge base the agent answers from", "sys.b.l3": "Sales and advertising analytics",

  "flow.k": "The customer journey",
  "flow.title": "From “how much?” to a shipping waybill",
  "flow.intro": "Five steps a manager used to do by hand — the AI agent now handles them itself. Scroll to see each step in the chat.",
  "s1.t": "Recognises the product from anything", "s1.d": "A photo, a repost, a reel, an SKU — even when the customer just forwards an ad.",
  "s2.t": "Picks the size and colour", "s2.d": "By height and weight or the size chart. Understands “I want two different colours”.",
  "s3.t": "Places the order", "s3.d": "Collects full name, phone, city and Nova Poshta branch — parses an address written in any format.",
  "s4.t": "Reconciles payment on its own", "s4.d": "Offers payment methods one by one and checks whether the money has arrived.",
  "s5.t": "Upsells — and answers honestly", "s5.d": "Suggests a relevant upsell at checkout. Says “I don't know” and calls a human when a fact isn't in the knowledge base.",
  "chat.online": "AI agent online", "chat.note": "Illustrative conversation",

  "ho.k": "Human in the loop",
  "ho.title": "It knows when to call a human",
  "ho.intro": "The AI doesn't pretend to know everything. When a person is needed, the conversation is handed over instantly — and every such case makes the system smarter.",
  "ho.1.t": "A complaint, a return, “I want a human”", "ho.1.d": "Instant handover to a manager — no delay and no loops.",
  "ho.2.t": "No answer in the knowledge base", "ho.2.d": "The conversation is passed to a person gracefully instead of getting stuck repeating itself.",
  "ho.3.t": "Every case is a lesson for the system", "ho.3.d": "A Telegram notification + a draft in the knowledge base. Next time the bot answers itself — and handovers get rarer every week.",
  "loop.1": "Unanswered question", "loop.2": "Telegram alert", "loop.3": "Manager replies", "loop.4": "Draft in knowledge base", "loop.5": "Next time — the bot answers",

  "cat.k": "Fineko CRM",
  "cat.title": "One catalog, one source of truth — for the bot and the manager",
  "cat.intro": "The AI agent answers with exactly what's in the CRM. Update a price or stock level — the bot already knows.",
  "cat.1.t": "Products with variants", "cat.1.d": "Colour, size, volume pricing, size charts, bundles of several items.",
  "cat.2.t": "Shop knowledge base", "cat.2.d": "Q&A per product, category or the whole shop — what the AI agent answers with.",
  "cat.3.t": "Suppliers and unit cost", "cat.3.d": "Transparent margin on every product — see your real profitability.",
  "cat.4.t": "Multi-tenancy", "cat.4.d": "Every shop is a separate, secure space with its own API key.",

  "an.k": "Analytics",
  "an.title": "See your business instead of guessing",
  "an.intro": "Everything happening in the business — in one dashboard. No separate Excel files, no manual reports.",
  "an.panel": "Fineko dashboard",
  "mod.sales": "Sales", "mod.ads": "Ads", "mod.chats": "Chats", "mod.products": "Products",
  "mod.sales.d": "Orders, revenue and top products for any period.",
  "mod.ads.d": "Every ad is linked to a product — see which post or campaign drove the sales.",
  "mod.chats.d": "Every conversation is tracked: what it cost, how it ended, whether a manager was needed.",
  "mod.products.d": "Most-asked-about products, plus margin and unit cost for each item.",
  "an.1.t": "Sales dashboard", "an.1.d": "Orders, revenue and top products for any period.",
  "an.2.t": "Ads linked to products", "an.2.d": "See exactly which post or campaign drove the sales.",
  "an.3.t": "Every conversation tracked", "an.3.d": "What it cost, how it ended, whether a manager was needed.",

  "res.k": "Results",
  "res.title": "Already running at a real clothing store",
  "res.intro": "Not a prototype or a pitch demo — a live shop, real customers, real orders.",
  "res.1.t": "Conversations a day", "res.1.d": "Handled by the AI agent with no manager involved.",
  "res.2.t": "Orders placed", "res.2.d": "Fully on its own — from the first message to confirmation.",
  "res.3.t": "Non-stop", "res.3.d": "Including night-time orders that would otherwise go to competitors.",
  "res.src": "Data from a live store on the Fineko platform, September 2026",

  "cost.k": "Economics",
  "cost.title": "A conversation costs about 1 hryvnia",
  "cost.intro": "A human manager is a fixed salary regardless of workload. The AI agent charges for exactly the work that happened.",
  "cmp.h0": "Parameter", "cmp.h1": "Human manager", "cmp.h2": "Fineko AI agent",
  "cmp.r1": "Cost", "cmp.r1a": "Fixed salary", "cmp.r1b": "≈ ₴1 / conversation, ≈ ₴15 / order",
  "cmp.r2": "Hours", "cmp.r2a": "8–10 h/day",
  "cmp.r3": "Reliability", "cmp.r3a": "Gets tired, gets sick, quits", "cmp.r3b": "Instant reply, every time",
  "cmp.r4": "Scale", "cmp.r4a": "Limited by one person", "cmp.r4b": "Unlimited",
  "cost.callout": "<span>Under a typical workload it's <b>3–5× cheaper</b> than the salary of a human manager doing the same amount of work.</span>",
  "calc.t": "Estimate it for your shop",
  "calc.d": "Based on ≈ ₴1 per conversation. Enter your own salary figure.",
  "calc.conv": "Conversations per day", "calc.salary": "Manager salary, ₴/month",
  "calc.human": "Manager", "calc.ai": "Fineko AI agent",
  "calc.cheaper": "cheaper than a manager's salary",
  "calc.pricier": "At this workload a manager costs less",
  "calc.month": "₴/mo",
  "calc.fine": "Rough estimate: 30 days × conversations × ≈₴1. One-time setup ($700) not included.",

  "pr.k": "Pricing",
  "pr.title": "A simple, transparent model",
  "pr.1.tag": "One-time setup", "pr.1.once": "once",
  "pr.1.d": "Instagram connection, catalog and knowledge-base setup, configured around your payment and delivery processes.",
  "pr.2.tag": "Pay as you go", "pr.2.unit": "AI token cost",
  "pr.2.d": "2× the cost of the AI tokens used. This covers size and colour matching, replies and payment reconciliation. Technical support included.",
  "pr.note": "No fixed monthly subscription “just in case” — you pay for exactly the conversations that actually happened.",

  "end.title": "A salesperson who never sleeps",
  "end.d": "Hand Direct over to the AI agent and keep the full picture of your business in one dashboard.",
  "end.cta": "Back to top ↑",
  "foot": "AI salesperson & CRM for Instagram shops"
};
